Repository philipuriarte/Automata-Project, pull requests merged in 2023-06, with the labels that each got.

#5 Feature string validation
  app.py
  utils.py
Labels: enhancement

#6 Feature animate dfa
  app.py
  utils.py
Labels: enhancement

#8 Readme update
  readme.md
Labels: documentation

#9 Develop to Main 06
  app.py
  readme.md
  utils.py
Labels: documentation, enhancement
